export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET'

export const ACCOUNT_SET = 'ACCOUNT_SET'
export const ACCOUNT_UNSET = 'ACCOUNT_UNSET'

export const REQUEST_API_DATA = 'REQUEST_API_DATA'
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA'
export const RECEIVE_API_FAILED = 'RECEIVE_API_FAILED'

export const SUBMIT_FORM = 'SUBMIT_FORM'
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS'
export const SUBMIT_FORM_ERROR = 'SUBMIT_FORM_ERROR'
export const SUBMIT_FORM_RESET = 'SUBMIT_FORM_RESET'
