export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET'

export const ACCOUNT_SET = 'ACCOUNT_SET'
export const ACCOUNT_UNSET = 'ACCOUNT_UNSET'
