/**
 * @Author: Junar B. Alinsub <Narnia1991>
 * @Date:   2017-12-27T02:32:08+08:00
 * @Email:  junaralinsub2@gmail.com
 * @Filename: user_info.js
 * @Last modified by:   Junar B. Alinsub
 * @Last modified time: 2018-01-03T13:41:48+08:00
 * @License: MIT
 * @Copyright: use it however you like, just buy me coffee next time
 */

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('user_info')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('user_info').insert([
        {
          first_name: 'Taylor',
          middle_name: 'Spence',
          last_name: 'Newman',
          address_1: '105 Albemarle Road',
          address_2: 'Bradford Street',
          city: 2767,
          country: 'NGA',
          phone_number: ' (866) 497-3411',
          cell_number: ' (916) 466-3214',
          birth_date: '12/12/1980',
          gender: 'Male',
          e_mail: 'taylornewman@peticular.com',
          date_created: '5/19/2017',
          date_updated: '5/19/2017'
        },
        {
          first_name: 'Karina',
          middle_name: 'Mercado',
          last_name: 'Cochran',
          address_1: '808 Utica Avenue',
          address_2: 'Fane Court',
          city: 1079,
          country: 'IND',
          phone_number: ' (927) 567-3338',
          cell_number: ' (989) 563-3371',
          birth_date: '2/17/1987',
          gender: 'Male',
          e_mail: 'karinacochran@peticular.com',
          date_created: '7/9/2016',
          date_updated: '7/9/2016'
        },
        {
          first_name: 'Harriett',
          middle_name: 'Golden',
          last_name: 'Boone',
          address_1: '773 Christopher Avenue',
          address_2: 'Brevoort Place',
          city: 3135,
          country: 'DEU',
          phone_number: ' (802) 408-2232',
          cell_number: ' (855) 562-3693',
          birth_date: '9/19/1982',
          gender: 'Female',
          e_mail: 'harriettboone@peticular.com',
          date_created: '3/21/2013',
          date_updated: '3/21/2013'
        },
        {
          first_name: 'Montoya',
          middle_name: 'Wheeler',
          last_name: 'Oliver',
          address_1: '949 Knight Court',
          address_2: 'Robert Street',
          city: 3363,
          country: 'TUR',
          phone_number: ' (862) 553-3353',
          cell_number: ' (996) 565-3120',
          birth_date: '5/11/1970',
          gender: 'Male',
          e_mail: 'montoyaoliver@peticular.com',
          date_created: '1/22/2012',
          date_updated: '1/22/2012'
        },
        {
          first_name: 'Genevieve',
          middle_name: 'Houston',
          last_name: 'Odom',
          address_1: '775 Lloyd Street',
          address_2: 'Conway Street',
          city: 2248,
          country: 'CHN',
          phone_number: ' (962) 577-2541',
          cell_number: ' (980) 448-2165',
          birth_date: '2/10/1980',
          gender: 'Female',
          e_mail: 'genevieveodom@peticular.com',
          date_created: '10/3/2012',
          date_updated: '10/3/2012'
        },
        {
          first_name: 'Karin',
          middle_name: 'Christensen',
          last_name: 'Maddox',
          address_1: '979 Quentin Street',
          address_2: 'Beacon Court',
          city: 2630,
          country: 'MEX',
          phone_number: ' (835) 490-3537',
          cell_number: ' (854) 492-3938',
          birth_date: '6/23/1992',
          gender: 'Female',
          e_mail: 'karinmaddox@peticular.com',
          date_created: '11/24/2010',
          date_updated: '11/24/2010'
        },
        {
          first_name: 'Ada',
          middle_name: 'Lloyd',
          last_name: 'Potter',
          address_1: '248 Forest Place',
          address_2: 'Jackson Place',
          city: 713,
          country: 'ZAF',
          phone_number: ' (836) 472-2455',
          cell_number: ' (846) 597-3392',
          birth_date: '1/24/1961',
          gender: 'Male',
          e_mail: 'adapotter@peticular.com',
          date_created: '2/16/2015',
          date_updated: '2/16/2015'
        },
        {
          first_name: 'Fletcher',
          middle_name: 'Ward',
          last_name: 'Combs',
          address_1: '760 Fleet Place',
          address_2: 'Stratford Road',
          city: 3354,
          country: 'TUN',
          phone_number: ' (862) 462-3479',
          cell_number: ' (987) 474-2243',
          birth_date: '2/26/1978',
          gender: 'Female',
          e_mail: 'fletchercombs@peticular.com',
          date_created: '11/27/2014',
          date_updated: '11/27/2014'
        },
        {
          first_name: 'Mcguire',
          middle_name: 'Richmond',
          last_name: 'Cabrera',
          address_1: '916 Quay Street',
          address_2: 'Oceanic Avenue',
          city: 803,
          country: 'PHL',
          phone_number: ' (933) 501-3203',
          cell_number: ' (819) 527-2329',
          birth_date: '5/7/1963',
          gender: 'Female',
          e_mail: 'mcguirecabrera@peticular.com',
          date_created: '1/16/2016',
          date_updated: '1/16/2016'
        },
        {
          first_name: 'Addie',
          middle_name: 'Henson',
          last_name: 'Bradford',
          address_1: '767 Crescent Street',
          address_2: 'Harbor Lane',
          city: 2873,
          country: 'PAK',
          phone_number: ' (838) 460-3644',
          cell_number: ' (867) 500-3325',
          birth_date: '3/16/1976',
          gender: 'Female',
          e_mail: 'addiebradford@peticular.com',
          date_created: '7/1/2017',
          date_updated: '7/1/2017'
        },
        {
          first_name: 'Augusta',
          middle_name: 'Cortez',
          last_name: 'Graham',
          address_1: '828 Maple Street',
          address_2: 'Lynch Street',
          city: 1556,
          country: 'JPN',
          phone_number: ' (994) 522-3382',
          cell_number: ' (892) 560-3478',
          birth_date: '8/6/1963',
          gender: 'Male',
          e_mail: 'augustagraham@peticular.com',
          date_created: '7/25/2017',
          date_updated: '7/25/2017'
        },
        {
          first_name: 'Chrystal',
          middle_name: 'Kramer',
          last_name: 'Vega',
          address_1: '712 Merit Court',
          address_2: 'Seeley Street',
          city: 1548,
          country: 'JPN',
          phone_number: ' (814) 481-2560',
          cell_number: ' (872) 554-3834',
          birth_date: '8/17/1966',
          gender: 'Male',
          e_mail: 'chrystalvega@peticular.com',
          date_created: '3/2/2015',
          date_updated: '3/2/2015'
        },
        {
          first_name: 'Cobb',
          middle_name: 'Ellison',
          last_name: 'Larsen',
          address_1: '100 Neptune Court',
          address_2: 'Stuart Street',
          city: 2654,
          country: 'MEX',
          phone_number: ' (948) 421-2035',
          cell_number: ' (849) 449-2088',
          birth_date: '2/22/1983',
          gender: 'Male',
          e_mail: 'cobblarsen@peticular.com',
          date_created: '7/21/2015',
          date_updated: '7/21/2015'
        },
        {
          first_name: 'Audra',
          middle_name: 'Herring',
          last_name: 'Flores',
          address_1: '280 Colby Court',
          address_2: 'Rugby Road',
          city: 314,
          country: 'BRA',
          phone_number: ' (910) 442-2833',
          cell_number: ' (914) 456-3495',
          birth_date: '10/23/1980',
          gender: 'Male',
          e_mail: 'audraflores@peticular.com',
          date_created: '8/1/2017',
          date_updated: '8/1/2017'
        },
        {
          first_name: 'Mack',
          middle_name: 'Hodge',
          last_name: 'Espinoza',
          address_1: '993 Noble Street',
          address_2: 'Bushwick Avenue',
          city: 2703,
          country: 'MOZ',
          phone_number: ' (993) 559-2534',
          cell_number: ' (819) 523-3596',
          birth_date: '6/10/1964',
          gender: 'Female',
          e_mail: 'mackespinoza@peticular.com',
          date_created: '4/26/2015',
          date_updated: '4/26/2015'
        },
        {
          first_name: 'Bobbi',
          middle_name: 'Barton',
          last_name: 'Bridges',
          address_1: '931 Dewey Place',
          address_2: 'Sunnyside Avenue',
          city: 3220,
          country: 'LKA',
          phone_number: ' (983) 546-3848',
          cell_number: ' (941) 495-3963',
          birth_date: '10/12/1961',
          gender: 'Female',
          e_mail: 'bobbibridges@peticular.com',
          date_created: '1/6/2013',
          date_updated: '1/6/2013'
        },
        {
          first_name: 'Thelma',
          middle_name: 'Turner',
          last_name: 'Pollard',
          address_1: '506 Bethel Loop',
          address_2: 'Beadel Street',
          city: 2010,
          country: 'CHN',
          phone_number: ' (953) 418-2034',
          cell_number: ' (961) 468-2679',
          birth_date: '10/31/1985',
          gender: 'Female',
          e_mail: 'thelmapollard@peticular.com',
          date_created: '10/27/2010',
          date_updated: '10/27/2010'
        },
        {
          first_name: 'Meghan',
          middle_name: 'Knowles',
          last_name: 'Snider',
          address_1: '973 Autumn Avenue',
          address_2: 'Beayer Place',
          city: 2708,
          country: 'MOZ',
          phone_number: ' (858) 458-3744',
          cell_number: ' (868) 561-2130',
          birth_date: '5/13/1986',
          gender: 'Male',
          e_mail: 'meghansnider@peticular.com',
          date_created: '9/21/2013',
          date_updated: '9/21/2013'
        },
        {
          first_name: 'Sarah',
          middle_name: 'Parks',
          last_name: 'Hoffman',
          address_1: '682 Lacon Court',
          address_2: 'Clifton Place',
          city: 879,
          country: 'PHL',
          phone_number: ' (858) 488-2036',
          cell_number: ' (909) 452-2927',
          birth_date: '10/24/1968',
          gender: 'Male',
          e_mail: 'sarahhoffman@peticular.com',
          date_created: '4/29/2014',
          date_updated: '4/29/2014'
        },
        {
          first_name: 'Stevens',
          middle_name: 'Russell',
          last_name: 'Baxter',
          address_1: '314 Ovington Avenue',
          address_2: 'Bridgewater Street',
          city: 1007,
          country: 'IDN',
          phone_number: ' (841) 474-3046',
          cell_number: ' (904) 571-3356',
          birth_date: '4/8/1993',
          gender: 'Female',
          e_mail: 'stevensbaxter@peticular.com',
          date_created: '11/17/2014',
          date_updated: '11/17/2014'
        },
        {
          first_name: 'Juana',
          middle_name: 'Newton',
          last_name: 'Fuller',
          address_1: '947 Melba Court',
          address_2: 'Columbus Place',
          city: 229,
          country: 'BRA',
          phone_number: ' (960) 430-3079',
          cell_number: ' (977) 404-2900',
          birth_date: '6/3/1971',
          gender: 'Male',
          e_mail: 'juanafuller@peticular.com',
          date_created: '6/29/2010',
          date_updated: '6/29/2010'
        },
        {
          first_name: 'Loraine',
          middle_name: 'Burns',
          last_name: 'Thomas',
          address_1: '633 Hampton Place',
          address_2: 'Meserole Avenue',
          city: 1373,
          country: 'IRQ',
          phone_number: '(900) 468-3372',
          cell_number: '(801) 402-2869',
          birth_date: '11/24/1990',
          gender: 'Female',
          e_mail: 'lorainethomas@memora.com',
          date_created: '5/19/2011',
          date_updated: '5/19/2011'
        },
        {
          first_name: 'Deirdre',
          middle_name: 'Watts',
          last_name: 'Mcclain',
          address_1: '451 Fanchon Place',
          address_2: 'Vermont Street',
          city: 2785,
          country: 'NGA',
          phone_number: '(819) 464-2679',
          cell_number: '(973) 537-2273',
          birth_date: '12/18/1967',
          gender: 'Male',
          e_mail: 'deirdremcclain@memora.com',
          date_created: '8/14/2015',
          date_updated: '8/14/2015'
        },
        {
          first_name: 'Lelia',
          middle_name: 'Knight',
          last_name: 'Burris',
          address_1: '346 Willmohr Street',
          address_2: 'Ridgewood Avenue',
          city: 1436,
          country: 'IRN',
          phone_number: '(813) 600-2411',
          cell_number: '(978) 562-3576',
          birth_date: '9/4/1971',
          gender: 'Female',
          e_mail: 'leliaburris@memora.com',
          date_created: '2/1/2014',
          date_updated: '2/1/2014'
        },
        {
          first_name: 'Owens',
          middle_name: 'Pennington',
          last_name: 'Mcleod',
          address_1: '296 Banner Avenue',
          address_2: 'Ellery Street',
          city: 3901,
          country: 'USA',
          phone_number: '(847) 473-3130',
          cell_number: '(911) 414-2001',
          birth_date: '6/4/1973',
          gender: 'Male',
          e_mail: 'owensmcleod@memora.com',
          date_created: '9/2/2012',
          date_updated: '9/2/2012'
        },
        {
          first_name: 'Valenzuela',
          middle_name: 'Chen',
          last_name: 'Roth',
          address_1: '210 Havens Place',
          address_2: 'Brooklyn Avenue',
          city: 162,
          country: 'BGD',
          phone_number: '(882) 552-2556',
          cell_number: '(848) 500-2890',
          birth_date: '10/14/1981',
          gender: 'Male',
          e_mail: 'valenzuelaroth@memora.com',
          date_created: '5/26/2016',
          date_updated: '5/26/2016'
        },
        {
          first_name: 'Angela',
          middle_name: 'Weber',
          last_name: 'Owens',
          address_1: '234 Baughman Place',
          address_2: 'Vandervoort Avenue',
          city: 844,
          country: 'PHL',
          phone_number: '(819) 469-2359',
          cell_number: '(985) 557-3735',
          birth_date: '2/6/1973',
          gender: 'Female',
          e_mail: 'angelaowens@memora.com',
          date_created: '8/12/2010',
          date_updated: '8/12/2010'
        },
        {
          first_name: 'Daugherty',
          middle_name: 'Jacobson',
          last_name: 'Downs',
          address_1: '159 Riverdale Avenue',
          address_2: 'Wogan Terrace',
          city: 202,
          country: 'BIH',
          phone_number: '(844) 462-2198',
          cell_number: '(963) 425-2656',
          birth_date: '1/22/1995',
          gender: 'Female',
          e_mail: 'daughertydowns@memora.com',
          date_created: '7/7/2014',
          date_updated: '7/7/2014'
        },
        {
          first_name: 'Page',
          middle_name: 'Lowery',
          last_name: 'Maxwell',
          address_1: '893 Grant Avenue',
          address_2: 'Delevan Street',
          city: 2400,
          country: 'KOR',
          phone_number: '(823) 493-2460',
          cell_number: '(866) 498-2151',
          birth_date: '1/5/1968',
          gender: 'Female',
          e_mail: 'pagemaxwell@memora.com',
          date_created: '12/8/2016',
          date_updated: '12/8/2016'
        },
        {
          first_name: 'Barber',
          middle_name: 'Warner',
          last_name: 'Kerr',
          address_1: '828 Bath Avenue',
          address_2: 'Clarkson Avenue',
          city: 758,
          country: 'ETH',
          phone_number: '(820) 522-2442',
          cell_number: '(822) 596-2270',
          birth_date: '12/17/1966',
          gender: 'Female',
          e_mail: 'barberkerr@memora.com',
          date_created: '2/18/2016',
          date_updated: '2/18/2016'
        },
        {
          first_name: 'Dotson',
          middle_name: 'Mccullough',
          last_name: 'Holland',
          address_1: '785 Newkirk Avenue',
          address_2: 'Bleecker Street',
          city: 1312,
          country: 'IND',
          phone_number: '(932) 471-3904',
          cell_number: '(835) 454-3204',
          birth_date: '5/3/1982',
          gender: 'Female',
          e_mail: 'dotsonholland@memora.com',
          date_created: '11/26/2012',
          date_updated: '11/26/2012'
        },
        {
          first_name: 'Karyn',
          middle_name: 'Charles',
          last_name: 'Leon',
          address_1: '305 Rapelye Street',
          address_2: 'Alabama Avenue',
          city: 2135,
          country: 'CHN',
          phone_number: '(957) 467-3599',
          cell_number: '(943) 427-3743',
          birth_date: '1/7/1965',
          gender: 'Male',
          e_mail: 'karynleon@memora.com',
          date_created: '8/3/2014',
          date_updated: '8/3/2014'
        },
        {
          first_name: 'Elvira',
          middle_name: 'Baldwin',
          last_name: 'Solomon',
          address_1: '520 Lexington Avenue',
          address_2: 'Ralph Avenue',
          city: 2081,
          country: 'CHN',
          phone_number: '(892) 509-2893',
          cell_number: '(870) 410-2514',
          birth_date: '2/10/1970',
          gender: 'Female',
          e_mail: 'elvirasolomon@memora.com',
          date_created: '5/7/2015',
          date_updated: '5/7/2015'
        },
        {
          first_name: 'Cooke',
          middle_name: 'Vaughn',
          last_name: 'Mullins',
          address_1: '708 Navy Street',
          address_2: 'Sackman Street',
          city: 3540,
          country: 'VEN',
          phone_number: '(865) 509-3292',
          cell_number: '(935) 491-3921',
          birth_date: '5/1/1972',
          gender: 'Female',
          e_mail: 'cookemullins@memora.com',
          date_created: '5/26/2014',
          date_updated: '5/26/2014'
        },
        {
          first_name: 'Margret',
          middle_name: 'Stout',
          last_name: 'Stone',
          address_1: '603 Stockholm Street',
          address_2: 'Sackett Street',
          city: 1779,
          country: 'JPN',
          phone_number: '(958) 457-2988',
          cell_number: '(917) 585-3249',
          birth_date: '6/11/1996',
          gender: 'Female',
          e_mail: 'margretstone@memora.com',
          date_created: '8/5/2017',
          date_updated: '8/5/2017'
        },
        {
          first_name: 'Jenny',
          middle_name: 'Tanner',
          last_name: 'Frederick',
          address_1: '246 Scott Avenue',
          address_2: 'Norfolk Street',
          city: 73,
          country: 'ARG',
          phone_number: '(961) 414-3850',
          cell_number: '(885) 473-3030',
          birth_date: '10/19/1967',
          gender: 'Male',
          e_mail: 'jennyfrederick@memora.com',
          date_created: '5/8/2016',
          date_updated: '5/8/2016'
        },
        {
          first_name: 'Nash',
          middle_name: 'Blackwell',
          last_name: 'Oneil',
          address_1: '596 Lincoln Place',
          address_2: 'Tech Place',
          city: 222,
          country: 'BRA',
          phone_number: '(834) 471-3656',
          cell_number: '(895) 422-2331',
          birth_date: '10/1/1993',
          gender: 'Male',
          e_mail: 'nashoneil@memora.com',
          date_created: '7/2/2014',
          date_updated: '7/2/2014'
        },
        {
          first_name: 'Sallie',
          middle_name: 'Medina',
          last_name: 'Jones',
          address_1: '746 Seabring Street',
          address_2: 'Bills Place',
          city: 1084,
          country: 'IND',
          phone_number: '(860) 596-3603',
          cell_number: '(972) 527-3147',
          birth_date: '11/15/1971',
          gender: 'Female',
          e_mail: 'salliejones@memora.com',
          date_created: '9/4/2010',
          date_updated: '9/4/2010'
        },
        {
          first_name: 'Rosario',
          middle_name: 'Clay',
          last_name: 'Pacheco',
          address_1: '274 Howard Avenue',
          address_2: 'Clara Street',
          city: 296,
          country: 'BRA',
          phone_number: '(855) 441-2961',
          cell_number: '(823) 442-2902',
          birth_date: '8/17/1970',
          gender: 'Female',
          e_mail: 'rosariopacheco@memora.com',
          date_created: '12/1/2017',
          date_updated: '12/1/2017'
        },
        {
          first_name: 'Irma',
          middle_name: 'Langley',
          last_name: 'Flores',
          address_1: '281 Beacon Court',
          address_2: 'Highland Avenue',
          city: 2824,
          country: 'PAK',
          phone_number: '(913) 422-2294',
          cell_number: '(862) 581-3112',
          birth_date: '4/24/1989',
          gender: 'Female',
          e_mail: 'irmaflores@memora.com',
          date_created: '4/20/2010',
          date_updated: '4/20/2010'
        },
        {
          first_name: 'Thornton',
          middle_name: 'Page',
          last_name: 'Levine',
          address_1: '646 Gold Street',
          address_2: 'King Street',
          city: 869,
          country: 'PHL',
          phone_number: '(879) 553-2246',
          cell_number: '(900) 464-3633',
          birth_date: '11/6/1977',
          gender: 'Male',
          e_mail: 'thorntonlevine@memora.com',
          date_created: '11/7/2014',
          date_updated: '11/7/2014'
        },
        {
          first_name: 'Barnett',
          middle_name: 'Haney',
          last_name: 'Bird',
          address_1: '729 Lewis Avenue',
          address_2: 'Lawton Street',
          city: 3532,
          country: 'BLR',
          phone_number: '(815) 563-2134',
          cell_number: '(900) 587-3304',
          birth_date: '11/8/1991',
          gender: 'Female',
          e_mail: 'barnettbird@memora.com',
          date_created: '4/28/2012',
          date_updated: '4/28/2012'
        },
        {
          first_name: 'Brooke',
          middle_name: 'Moore',
          last_name: 'Vasquez',
          address_1: '762 Maujer Street',
          address_2: 'Hope Street',
          city: 3367,
          country: 'TUR',
          phone_number: '(801) 558-3811',
          cell_number: '(927) 539-2315',
          birth_date: '2/7/1997',
          gender: 'Male',
          e_mail: 'brookevasquez@memora.com',
          date_created: '2/11/2015',
          date_updated: '2/11/2015'
        },
        {
          first_name: 'Munoz',
          middle_name: 'Freeman',
          last_name: 'Berger',
          address_1: '904 Chester Street',
          address_2: 'Polhemus Place',
          city: 3559,
          country: 'VEN',
          phone_number: '(958) 425-2265',
          cell_number: '(902) 514-3655',
          birth_date: '10/8/1980',
          gender: 'Female',
          e_mail: 'munozberger@memora.com',
          date_created: '3/7/2013',
          date_updated: '3/7/2013'
        },
        {
          first_name: 'Whitaker',
          middle_name: 'Mcpherson',
          last_name: 'Bruce',
          address_1: '809 Congress Street',
          address_2: 'Bayview Place',
          city: 126,
          country: 'ARM',
          phone_number: '(854) 445-2661',
          cell_number: '(823) 545-3746',
          birth_date: '7/21/1969',
          gender: 'Male',
          e_mail: 'whitakerbruce@memora.com',
          date_created: '7/13/2015',
          date_updated: '7/13/2015'
        },
        {
          first_name: 'Lilia',
          middle_name: 'Whitaker',
          last_name: 'Combs',
          address_1: '215 Coles Street',
          address_2: 'Claver Place',
          city: 3614,
          country: 'RUS',
          phone_number: '(963) 470-3329',
          cell_number: '(953) 572-3055',
          birth_date: '11/12/1965',
          gender: 'Female',
          e_mail: 'liliacombs@memora.com',
          date_created: '2/19/2011',
          date_updated: '2/19/2011'
        },
        {
          first_name: 'Baker',
          middle_name: 'Dillard',
          last_name: 'May',
          address_1: '272 Sedgwick Place',
          address_2: 'Fuller Place',
          city: 1097,
          country: 'IND',
          phone_number: '(904) 408-3190',
          cell_number: '(901) 594-3465',
          birth_date: '3/15/1982',
          gender: 'Male',
          e_mail: 'bakermay@memora.com',
          date_created: '10/26/2011',
          date_updated: '10/26/2011'
        },
        {
          first_name: 'Elnora',
          middle_name: 'Sparks',
          last_name: 'Daniel',
          address_1: '928 Lorraine Street',
          address_2: 'Bulwer Place',
          city: 2356,
          country: 'KOR',
          phone_number: '(911) 505-2549',
          cell_number: '(951) 487-3423',
          birth_date: '7/17/1976',
          gender: 'Male',
          e_mail: 'elnoradaniel@memora.com',
          date_created: '11/15/2012',
          date_updated: '11/15/2012'
        },
        {
          first_name: 'Allyson',
          middle_name: 'Walker',
          last_name: 'Delgado',
          address_1: '591 Fleet Street',
          address_2: 'Dooley Street',
          city: 3672,
          country: 'RUS',
          phone_number: '(983) 546-3075',
          cell_number: '(837) 512-3580',
          birth_date: '11/1/1987',
          gender: 'Male',
          e_mail: 'allysondelgado@memora.com',
          date_created: '5/19/2012',
          date_updated: '5/19/2012'
        },
        {
          first_name: 'Nadine',
          middle_name: 'Weeks',
          last_name: 'Munoz',
          address_1: '247 Knickerbocker Avenue',
          address_2: 'Manhattan Court',
          city: 3294,
          country: 'TWN',
          phone_number: '(980) 557-2621',
          cell_number: '(906) 548-3167',
          birth_date: '11/9/1966',
          gender: 'Female',
          e_mail: 'nadinemunoz@memora.com',
          date_created: '12/30/2011',
          date_updated: '12/30/2011'
        },
        {
          first_name: 'Candice',
          middle_name: 'Mckenzie',
          last_name: 'Tillman',
          address_1: '783 Dahl Court',
          address_2: 'Oliver Street',
          city: 3762,
          country: 'RUS',
          phone_number: '(968) 465-3224',
          cell_number: '(890) 462-2382',
          birth_date: '8/11/1997',
          gender: 'Female',
          e_mail: 'candicetillman@memora.com',
          date_created: '5/24/2017',
          date_updated: '5/24/2017'
        },
        {
          first_name: 'Lorene',
          middle_name: 'Snider',
          last_name: 'Richard',
          address_1: '499 Ingraham Street',
          address_2: 'Fane Court',
          city: 3008,
          country: 'FRA',
          phone_number: '(916) 486-2335',
          cell_number: '(993) 412-3593',
          birth_date: '10/27/1974',
          gender: 'Female',
          e_mail: 'lorenerichard@memora.com',
          date_created: '10/17/2011',
          date_updated: '10/17/2011'
        },
        {
          first_name: 'Elba',
          middle_name: 'Rice',
          last_name: 'Kennedy',
          address_1: '118 Senator Street',
          address_2: 'Blake Court',
          city: 1403,
          country: 'IRN',
          phone_number: '(896) 465-3868',
          cell_number: '(825) 542-3143',
          birth_date: '5/12/1984',
          gender: 'Female',
          e_mail: 'elbakennedy@memora.com',
          date_created: '2/6/2012',
          date_updated: '2/6/2012'
        },
        {
          first_name: 'Patrica',
          middle_name: 'Guerra',
          last_name: 'Bean',
          address_1: '221 Cypress Avenue',
          address_2: 'Lewis Place',
          city: 596,
          country: 'ECU',
          phone_number: '(978) 534-2319',
          cell_number: '(995) 407-3601',
          birth_date: '5/17/1989',
          gender: 'Female',
          e_mail: 'patricabean@memora.com',
          date_created: '5/17/2017',
          date_updated: '5/17/2017'
        },
        {
          first_name: 'Aguilar',
          middle_name: 'Mays',
          last_name: 'Chang',
          address_1: '372 Exeter Street',
          address_2: 'Bayview Avenue',
          city: 1083,
          country: 'IND',
          phone_number: '(985) 572-3610',
          cell_number: '(958) 587-3746',
          birth_date: '11/18/1990',
          gender: 'Male',
          e_mail: 'aguilarchang@memora.com',
          date_created: '12/31/2011',
          date_updated: '12/31/2011'
        },
        {
          first_name: 'Macdonald',
          middle_name: 'Dixon',
          last_name: 'Cochran',
          address_1: '933 Atlantic Avenue',
          address_2: 'Diamond Street',
          city: 2687,
          country: 'MEX',
          phone_number: '(921) 510-2787',
          cell_number: '(879) 546-3244',
          birth_date: '7/27/1997',
          gender: 'Male',
          e_mail: 'macdonaldcochran@memora.com',
          date_created: '7/28/2010',
          date_updated: '7/28/2010'
        },
        {
          first_name: 'Tasha',
          middle_name: 'Pruitt',
          last_name: 'Davis',
          address_1: '954 Madison Street',
          address_2: 'Holt Court',
          city: 1338,
          country: 'IND',
          phone_number: '(983) 565-2384',
          cell_number: '(941) 460-3259',
          birth_date: '11/9/1996',
          gender: 'Female',
          e_mail: 'tashadavis@memora.com',
          date_created: '6/6/2017',
          date_updated: '6/6/2017'
        },
        {
          first_name: 'Kane',
          middle_name: 'Mcfadden',
          last_name: 'Reid',
          address_1: '488 Kay Court',
          address_2: 'Just Court',
          city: 2338,
          country: 'KOR',
          phone_number: '(825) 549-3007',
          cell_number: '(920) 568-3727',
          birth_date: '8/9/1983',
          gender: 'Male',
          e_mail: 'kanereid@memora.com',
          date_created: '7/8/2010',
          date_updated: '7/8/2010'
        },
        {
          first_name: 'Victoria',
          middle_name: 'Norton',
          last_name: 'Duke',
          address_1: '519 Conduit Boulevard',
          address_2: 'Dearborn Court',
          city: 1091,
          country: 'IND',
          phone_number: '(857) 467-2648',
          cell_number: '(835) 594-2174',
          birth_date: '9/15/1995',
          gender: 'Female',
          e_mail: 'victoriaduke@memora.com',
          date_created: '2/23/2013',
          date_updated: '2/23/2013'
        },
        {
          first_name: 'Casey',
          middle_name: 'Gutierrez',
          last_name: 'Gibson',
          address_1: '129 Kathleen Court',
          address_2: 'Gilmore Court',
          city: 1135,
          country: 'IND',
          phone_number: '(845) 598-3367',
          cell_number: '(859) 527-2537',
          birth_date: '3/6/1985',
          gender: 'Female',
          e_mail: 'caseygibson@memora.com',
          date_created: '11/21/2012',
          date_updated: '11/21/2012'
        },
        {
          first_name: 'Jimenez',
          middle_name: 'Davidson',
          last_name: 'Watkins',
          address_1: '808 Windsor Place',
          address_2: 'Lancaster Avenue',
          city: 1722,
          country: 'JPN',
          phone_number: '(883) 557-2666',
          cell_number: '(917) 438-3072',
          birth_date: '6/19/1975',
          gender: 'Male',
          e_mail: 'jimenezwatkins@memora.com',
          date_created: '9/16/2010',
          date_updated: '9/16/2010'
        },
        {
          first_name: 'Barker',
          middle_name: 'Nielsen',
          last_name: 'Velasquez',
          address_1: '314 Cass Place',
          address_2: 'Lynch Street',
          city: 1987,
          country: 'CHN',
          phone_number: '(979) 513-2810',
          cell_number: '(808) 521-2975',
          birth_date: '6/4/1963',
          gender: 'Male',
          e_mail: 'barkervelasquez@memora.com',
          date_created: '10/10/2017',
          date_updated: '10/10/2017'
        },
        {
          first_name: 'Mayra',
          middle_name: 'Williams',
          last_name: 'Trujillo',
          address_1: '378 Branton Street',
          address_2: 'Roosevelt Court',
          city: 3108,
          country: 'DEU',
          phone_number: '(886) 591-3453',
          cell_number: '(810) 577-3569',
          birth_date: '6/27/1962',
          gender: 'Male',
          e_mail: 'mayratrujillo@memora.com',
          date_created: '3/23/2017',
          date_updated: '3/23/2017'
        },
        {
          first_name: 'Robles',
          middle_name: 'Gamble',
          last_name: 'Murphy',
          address_1: '243 McDonald Avenue',
          address_2: 'Navy Walk',
          city: 1573,
          country: 'JPN',
          phone_number: '(863) 562-3275',
          cell_number: '(809) 445-3683',
          birth_date: '11/29/1970',
          gender: 'Female',
          e_mail: 'roblesmurphy@memora.com',
          date_created: '10/19/2010',
          date_updated: '10/19/2010'
        },
        {
          first_name: 'Haley',
          middle_name: 'Chapman',
          last_name: 'Elliott',
          address_1: '903 Love Lane',
          address_2: 'Ashford Street',
          city: 731,
          country: 'ZAF',
          phone_number: '(814) 477-3464',
          cell_number: '(987) 451-3370',
          birth_date: '3/18/1969',
          gender: 'Male',
          e_mail: 'haleyelliott@memora.com',
          date_created: '10/10/2016',
          date_updated: '10/10/2016'
        },
        {
          first_name: 'Lillie',
          middle_name: 'Sloan',
          last_name: 'Alvarado',
          address_1: '421 Waldane Court',
          address_2: 'Glenmore Avenue',
          city: 990,
          country: 'IDN',
          phone_number: '(940) 575-3028',
          cell_number: '(942) 575-3658',
          birth_date: '1/13/1977',
          gender: 'Male',
          e_mail: 'lilliealvarado@memora.com',
          date_created: '1/21/2010',
          date_updated: '1/21/2010'
        },
        {
          first_name: 'Cristina',
          middle_name: 'Carson',
          last_name: 'Castillo',
          address_1: '585 Brigham Street',
          address_2: 'College Place',
          city: 668,
          country: 'ESP',
          phone_number: '(995) 555-2563',
          cell_number: '(964) 529-2360',
          birth_date: '5/24/1997',
          gender: 'Female',
          e_mail: 'cristinacastillo@memora.com',
          date_created: '5/12/2013',
          date_updated: '5/12/2013'
        },
        {
          first_name: 'Neva',
          middle_name: 'Rose',
          last_name: 'Stanley',
          address_1: '631 Kenmore Court',
          address_2: 'Losee Terrace',
          city: 2081,
          country: 'CHN',
          phone_number: '(863) 519-2028',
          cell_number: '(875) 406-2156',
          birth_date: '11/14/1996',
          gender: 'Female',
          e_mail: 'nevastanley@memora.com',
          date_created: '10/6/2013',
          date_updated: '10/6/2013'
        },
        {
          first_name: 'Annie',
          middle_name: 'Hensley',
          last_name: 'Rosario',
          address_1: '763 Bartlett Street',
          address_2: 'Beaver Street',
          city: 2327,
          country: 'PRK',
          phone_number: '(880) 435-3307',
          cell_number: '(960) 477-3754',
          birth_date: '3/21/1979',
          gender: 'Male',
          e_mail: 'annierosario@memora.com',
          date_created: '2/6/2014',
          date_updated: '2/6/2014'
        },
        {
          first_name: 'Ewing',
          middle_name: 'Cooley',
          last_name: 'Humphrey',
          address_1: '492 Otsego Street',
          address_2: 'Noble Street',
          city: 1169,
          country: 'IND',
          phone_number: '(983) 449-2005',
          cell_number: '(971) 527-2860',
          birth_date: '3/11/1978',
          gender: 'Male',
          e_mail: 'ewinghumphrey@memora.com',
          date_created: '11/29/2017',
          date_updated: '11/29/2017'
        },
        {
          first_name: 'Iva',
          middle_name: 'Randolph',
          last_name: 'Mueller',
          address_1: '205 Linden Street',
          address_2: 'Schenck Avenue',
          city: 291,
          country: 'BRA',
          phone_number: '(871) 438-3094',
          cell_number: '(978) 593-2645',
          birth_date: '5/22/1994',
          gender: 'Male',
          e_mail: 'ivamueller@memora.com',
          date_created: '6/25/2013',
          date_updated: '6/25/2013'
        },
        {
          first_name: 'Kemp',
          middle_name: 'Marshall',
          last_name: 'Bryant',
          address_1: '287 Regent Place',
          address_2: 'Carroll Street',
          city: 3403,
          country: 'TUR',
          phone_number: '(871) 468-3695',
          cell_number: '(886) 463-3019',
          birth_date: '5/9/1989',
          gender: 'Male',
          e_mail: 'kempbryant@memora.com',
          date_created: '10/5/2015',
          date_updated: '10/5/2015'
        },
        {
          first_name: 'Pauline',
          middle_name: 'Kirk',
          last_name: 'Emerson',
          address_1: '649 Erskine Loop',
          address_2: 'Ditmas Avenue',
          city: 2504,
          country: 'MAR',
          phone_number: '(822) 453-3782',
          cell_number: '(999) 595-2106',
          birth_date: '2/22/1974',
          gender: 'Female',
          e_mail: 'paulineemerson@memora.com',
          date_created: '12/1/2013',
          date_updated: '12/1/2013'
        },
        {
          first_name: 'Delores',
          middle_name: 'Hoffman',
          last_name: 'Kaufman',
          address_1: '229 Hull Street',
          address_2: 'Bennet Court',
          city: 3391,
          country: 'TUR',
          phone_number: '(981) 407-3257',
          cell_number: '(853) 543-3067',
          birth_date: '1/30/1962',
          gender: 'Male',
          e_mail: 'deloreskaufman@memora.com',
          date_created: '2/9/2012',
          date_updated: '2/9/2012'
        },
        {
          first_name: 'Hahn',
          middle_name: 'Horton',
          last_name: 'Bernard',
          address_1: '314 Bay Street',
          address_2: 'Barwell Terrace',
          city: 373,
          country: 'BRA',
          phone_number: '(952) 457-2985',
          cell_number: '(946) 455-3678',
          birth_date: '6/12/1962',
          gender: 'Female',
          e_mail: 'hahnbernard@memora.com',
          date_created: '4/14/2011',
          date_updated: '4/14/2011'
        },
        {
          first_name: 'Duffy',
          middle_name: 'Alston',
          last_name: 'Gregory',
          address_1: '183 Lester Court',
          address_2: 'Cooper Street',
          city: 846,
          country: 'PHL',
          phone_number: '(961) 517-2441',
          cell_number: '(937) 442-3766',
          birth_date: '1/12/1987',
          gender: 'Male',
          e_mail: 'duffygregory@memora.com',
          date_created: '2/22/2016',
          date_updated: '2/22/2016'
        },
        {
          first_name: 'Strickland',
          middle_name: 'Melendez',
          last_name: 'Odom',
          address_1: '302 Stuart Street',
          address_2: 'Quincy Street',
          city: 2574,
          country: 'MEX',
          phone_number: '(879) 494-3742',
          cell_number: '(805) 463-2312',
          birth_date: '3/10/1966',
          gender: 'Male',
          e_mail: 'stricklandodom@memora.com',
          date_created: '3/19/2015',
          date_updated: '3/19/2015'
        },
        {
          first_name: 'Patty',
          middle_name: 'Sutton',
          last_name: 'Cruz',
          address_1: '650 Jackson Place',
          address_2: 'Sullivan Place',
          city: 3884,
          country: 'USA',
          phone_number: '(966) 419-2380',
          cell_number: '(891) 560-3807',
          birth_date: '12/20/1965',
          gender: 'Male',
          e_mail: 'pattycruz@memora.com',
          date_created: '4/20/2010',
          date_updated: '4/20/2010'
        },
        {
          first_name: 'Dillon',
          middle_name: 'Wyatt',
          last_name: 'Witt',
          address_1: '486 Empire Boulevard',
          address_2: 'Plaza Street',
          city: 1960,
          country: 'CHN',
          phone_number: '(981) 468-2617',
          cell_number: '(908) 445-2358',
          birth_date: '1/9/1969',
          gender: 'Female',
          e_mail: 'dillonwitt@memora.com',
          date_created: '5/13/2012',
          date_updated: '5/13/2012'
        },
        {
          first_name: 'Gay',
          middle_name: 'Fuentes',
          last_name: 'Mccarty',
          address_1: '466 Homecrest Avenue',
          address_2: 'Wyckoff Avenue',
          city: 3514,
          country: 'UZB',
          phone_number: '(894) 587-3275',
          cell_number: '(999) 488-3280',
          birth_date: '10/14/1960',
          gender: 'Male',
          e_mail: 'gaymccarty@memora.com',
          date_created: '10/2/2015',
          date_updated: '10/2/2015'
        },
        {
          first_name: 'Rice',
          middle_name: 'Mann',
          last_name: 'Klein',
          address_1: '233 Garden Street',
          address_2: 'Matthews Court',
          city: 2139,
          country: 'CHN',
          phone_number: '(867) 554-3135',
          cell_number: '(901) 445-2547',
          birth_date: '3/25/1989',
          gender: 'Male',
          e_mail: 'riceklein@memora.com',
          date_created: '2/27/2014',
          date_updated: '2/27/2014'
        },
        {
          first_name: 'Bridgette',
          middle_name: 'Mooney',
          last_name: 'Decker',
          address_1: '103 Cleveland Street',
          address_2: 'Abbey Court',
          city: 3494,
          country: 'NZL',
          phone_number: '(895) 434-3568',
          cell_number: '(922) 453-2059',
          birth_date: '11/12/1973',
          gender: 'Male',
          e_mail: 'bridgettedecker@memora.com',
          date_created: '4/12/2015',
          date_updated: '4/12/2015'
        },
        {
          first_name: 'Greta',
          middle_name: 'Rojas',
          last_name: 'Hickman',
          address_1: '460 Gatling Place',
          address_2: 'Emerald Street',
          city: 2742,
          country: 'NGA',
          phone_number: '(968) 445-2023',
          cell_number: '(907) 546-3619',
          birth_date: '7/5/1964',
          gender: 'Female',
          e_mail: 'gretahickman@memora.com',
          date_created: '12/18/2013',
          date_updated: '12/18/2013'
        },
        {
          first_name: 'Wilkinson',
          middle_name: 'Hughes',
          last_name: 'Everett',
          address_1: '158 Crooke Avenue',
          address_2: 'Garden Place',
          city: 385,
          country: 'BRA',
          phone_number: '(850) 405-3407',
          cell_number: '(891) 520-2233',
          birth_date: '2/23/1983',
          gender: 'Female',
          e_mail: 'wilkinsoneverett@memora.com',
          date_created: '4/14/2013',
          date_updated: '4/14/2013'
        },
        {
          first_name: 'Briggs',
          middle_name: 'Brennan',
          last_name: 'Daniels',
          address_1: '539 Mersereau Court',
          address_2: 'Baltic Street',
          city: 3242,
          country: 'FIN',
          phone_number: '(900) 495-3339',
          cell_number: '(854) 553-3283',
          birth_date: '4/5/1996',
          gender: 'Male',
          e_mail: 'briggsdaniels@memora.com',
          date_created: '5/14/2013',
          date_updated: '5/14/2013'
        },
        {
          first_name: 'Savannah',
          middle_name: 'Vincent',
          last_name: 'Joseph',
          address_1: '873 Linwood Street',
          address_2: 'Ebony Court',
          city: 559,
          country: 'CHL',
          phone_number: '(834) 480-3988',
          cell_number: '(972) 501-2844',
          birth_date: '10/13/1979',
          gender: 'Male',
          e_mail: 'savannahjoseph@memora.com',
          date_created: '2/1/2017',
          date_updated: '2/1/2017'
        },
        {
          first_name: 'Mccullough',
          middle_name: 'Castaneda',
          last_name: 'Pate',
          address_1: '274 Amboy Street',
          address_2: 'Ryder Avenue',
          city: 1651,
          country: 'JPN',
          phone_number: '(862) 476-3024',
          cell_number: '(911) 577-3484',
          birth_date: '1/12/1990',
          gender: 'Female',
          e_mail: 'mcculloughpate@memora.com',
          date_created: '7/10/2016',
          date_updated: '7/10/2016'
        },
        {
          first_name: 'Bridges',
          middle_name: 'Payne',
          last_name: 'Ford',
          address_1: '601 Bassett Avenue',
          address_2: 'Fleet Place',
          city: 1982,
          country: 'CHN',
          phone_number: '(989) 438-3303',
          cell_number: '(896) 600-3696',
          birth_date: '2/6/1969',
          gender: 'Male',
          e_mail: 'bridgesford@memora.com',
          date_created: '5/10/2017',
          date_updated: '5/10/2017'
        },
        {
          first_name: 'Edwards',
          middle_name: 'Eaton',
          last_name: 'Cantrell',
          address_1: '742 Haring Street',
          address_2: 'Amersfort Place',
          city: 523,
          country: 'GBR',
          phone_number: '(959) 411-3719',
          cell_number: '(886) 523-2973',
          birth_date: '6/30/1995',
          gender: 'Female',
          e_mail: 'edwardscantrell@memora.com',
          date_created: '3/2/2012',
          date_updated: '3/2/2012'
        },
        {
          first_name: 'Marion',
          middle_name: 'Johns',
          last_name: 'Meyers',
          address_1: '563 Jerome Street',
          address_2: 'Chapel Street',
          city: 255,
          country: 'BRA',
          phone_number: '(909) 416-3772',
          cell_number: '(848) 560-2085',
          birth_date: '5/10/1988',
          gender: 'Female',
          e_mail: 'marionmeyers@memora.com',
          date_created: '7/4/2012',
          date_updated: '7/4/2012'
        },
        {
          first_name: 'Christine',
          middle_name: 'Christensen',
          last_name: 'Cleveland',
          address_1: '267 Hazel Court',
          address_2: 'Georgia Avenue',
          city: 54,
          country: '#N/A',
          phone_number: '(878) 536-2452',
          cell_number: '(882) 452-2765',
          birth_date: '8/22/1985',
          gender: 'Female',
          e_mail: 'christinecleveland@memora.com',
          date_created: '5/18/2015',
          date_updated: '5/18/2015'
        },
        {
          first_name: 'Sosa',
          middle_name: 'Ramos',
          last_name: 'Koch',
          address_1: '699 Paerdegat Avenue',
          address_2: 'Woodrow Court',
          city: 582,
          country: 'CHL',
          phone_number: '(948) 492-2091',
          cell_number: '(870) 551-2091',
          birth_date: '1/12/1960',
          gender: 'Male',
          e_mail: 'sosakoch@memora.com',
          date_created: '9/14/2014',
          date_updated: '9/14/2014'
        },
        {
          first_name: 'Silva',
          middle_name: 'Fields',
          last_name: 'Navarro',
          address_1: '575 Furman Avenue',
          address_2: 'Cornelia Street',
          city: 1320,
          country: 'IND',
          phone_number: '(989) 530-3902',
          cell_number: '(878) 571-3073',
          birth_date: '2/12/1966',
          gender: 'Male',
          e_mail: 'silvanavarro@memora.com',
          date_created: '11/27/2015',
          date_updated: '11/27/2015'
        },
        {
          first_name: 'Parker',
          middle_name: 'Merritt',
          last_name: 'Velez',
          address_1: '266 Driggs Avenue',
          address_2: 'Berriman Street',
          city: 4014,
          country: 'USA',
          phone_number: '(860) 468-2614',
          cell_number: '(906) 576-2586',
          birth_date: '2/1/1993',
          gender: 'Female',
          e_mail: 'parkervelez@memora.com',
          date_created: '12/29/2016',
          date_updated: '12/29/2016'
        },
        {
          first_name: 'Augusta',
          middle_name: 'Ratliff',
          last_name: 'Edwards',
          address_1: '127 Alton Place',
          address_2: 'Everett Avenue',
          city: 954,
          country: 'IDN',
          phone_number: '(971) 559-2848',
          cell_number: '(999) 507-2270',
          birth_date: '8/25/1985',
          gender: 'Male',
          e_mail: 'augustaedwards@memora.com',
          date_created: '5/1/2014',
          date_updated: '5/1/2014'
        },
        {
          first_name: 'Hale',
          middle_name: 'Talley',
          last_name: 'Alexander',
          address_1: '934 Maple Avenue',
          address_2: 'Boerum Street',
          city: 1274,
          country: 'IND',
          phone_number: '(918) 426-3530',
          cell_number: '(967) 553-3311',
          birth_date: '4/21/1982',
          gender: 'Female',
          e_mail: 'halealexander@memora.com',
          date_created: '7/28/2013',
          date_updated: '7/28/2013'
        },
        {
          first_name: 'Staci',
          middle_name: 'Glover',
          last_name: 'Jimenez',
          address_1: '588 Pioneer Street',
          address_2: 'Anthony Street',
          city: 2435,
          country: 'LVA',
          phone_number: '(925) 420-3201',
          cell_number: '(805) 517-2912',
          birth_date: '11/27/1965',
          gender: 'Female',
          e_mail: 'stacijimenez@memora.com',
          date_created: '1/26/2010',
          date_updated: '1/26/2010'
        },
        {
          first_name: 'Watson',
          middle_name: 'Nunez',
          last_name: 'Miles',
          address_1: '966 Harrison Avenue',
          address_2: 'Saratoga Avenue',
          city: 2730,
          country: 'NPL',
          phone_number: '(936) 504-3743',
          cell_number: '(970) 439-2783',
          birth_date: '2/2/1985',
          gender: 'Male',
          e_mail: 'watsonmiles@memora.com',
          date_created: '10/2/2013',
          date_updated: '10/2/2013'
        },
        {
          first_name: 'Kathrine',
          middle_name: 'Erickson',
          last_name: 'Morse',
          address_1: '619 Wolcott Street',
          address_2: 'Columbia Place',
          city: 308,
          country: 'BRA',
          phone_number: '(916) 467-2335',
          cell_number: '(966) 439-3813',
          birth_date: '7/16/1987',
          gender: 'Female',
          e_mail: 'kathrinemorse@memora.com',
          date_created: '11/12/2014',
          date_updated: '11/12/2014'
        },
        {
          first_name: 'Lourdes',
          middle_name: 'Hess',
          last_name: 'Riggs',
          address_1: '929 Cropsey Avenue',
          address_2: 'Troutman Street',
          city: 3435,
          country: 'UKR',
          phone_number: '(949) 554-2083',
          cell_number: '(877) 490-2949',
          birth_date: '4/19/1993',
          gender: 'Female',
          e_mail: 'lourdesriggs@memora.com',
          date_created: '12/8/2012',
          date_updated: '12/8/2012'
        },
        {
          first_name: 'Jasmine',
          middle_name: 'Patterson',
          last_name: 'Pittman',
          address_1: '175 Royce Street',
          address_2: 'Louisa Street',
          city: 2712,
          country: 'MMR',
          phone_number: '(979) 557-2303',
          cell_number: '(805) 587-2958',
          birth_date: '1/3/1986',
          gender: 'Female',
          e_mail: 'jasminepittman@memora.com',
          date_created: '10/21/2011',
          date_updated: '10/21/2011'
        },
        {
          first_name: 'Nicholson',
          middle_name: 'Wise',
          last_name: 'Richards',
          address_1: '467 Montague Terrace',
          address_2: 'Coleridge Street',
          city: 1182,
          country: 'IND',
          phone_number: '(998) 411-3676',
          cell_number: '(933) 509-3321',
          birth_date: '11/9/1975',
          gender: 'Female',
          e_mail: 'nicholsonrichards@memora.com',
          date_created: '2/13/2017',
          date_updated: '2/13/2017'
        },
        {
          first_name: 'Annmarie',
          middle_name: 'Fernandez',
          last_name: 'Mejia',
          address_1: '145 Jamison Lane',
          address_2: 'Nevins Street',
          city: 3446,
          country: 'UKR',
          phone_number: '(853) 591-2290',
          cell_number: '(891) 520-2741',
          birth_date: '2/6/1960',
          gender: 'Female',
          e_mail: 'annmariemejia@memora.com',
          date_created: '9/27/2014',
          date_updated: '9/27/2014'
        },
        {
          first_name: 'Goodman',
          middle_name: 'Wood',
          last_name: 'Zamora',
          address_1: '760 Danforth Street',
          address_2: 'Eckford Street',
          city: 3291,
          country: 'TWN',
          phone_number: '(812) 462-3765',
          cell_number: '(985) 511-2621',
          birth_date: '8/12/1976',
          gender: 'Male',
          e_mail: 'goodmanzamora@memora.com',
          date_created: '8/29/2017',
          date_updated: '8/29/2017'
        },
        {
          first_name: 'Young',
          middle_name: 'Cunningham',
          last_name: 'Peterson',
          address_1: '603 Arkansas Drive',
          address_2: 'Eldert Lane',
          city: 3150,
          country: 'DEU',
          phone_number: '(824) 584-3369',
          cell_number: '(994) 537-3711',
          birth_date: '8/25/1978',
          gender: 'Male',
          e_mail: 'youngpeterson@memora.com',
          date_created: '9/4/2017',
          date_updated: '9/4/2017'
        },
        {
          first_name: 'Stafford',
          middle_name: 'Slater',
          last_name: 'Torres',
          address_1: '909 Herkimer Street',
          address_2: 'Doscher Street',
          city: 1147,
          country: 'IND',
          phone_number: '(960) 534-3766',
          cell_number: '(860) 453-3706',
          birth_date: '11/11/1974',
          gender: 'Female',
          e_mail: 'staffordtorres@memora.com',
          date_created: '9/15/2011',
          date_updated: '9/15/2011'
        },
        {
          first_name: 'Curry',
          middle_name: 'Blair',
          last_name: 'Little',
          address_1: '647 Frank Court',
          address_2: 'Albemarle Road',
          city: 1567,
          country: 'JPN',
          phone_number: '(833) 523-3168',
          cell_number: '(930) 453-3584',
          birth_date: '2/12/1995',
          gender: 'Male',
          e_mail: 'currylittle@memora.com',
          date_created: '11/23/2011',
          date_updated: '11/23/2011'
        },
        {
          first_name: 'Alicia',
          middle_name: 'Robbins',
          last_name: 'Levy',
          address_1: '149 Murdock Court',
          address_2: 'Havemeyer Street',
          city: 3974,
          country: 'USA',
          phone_number: '(957) 418-3923',
          cell_number: '(870) 504-3564',
          birth_date: '4/13/1960',
          gender: 'Male',
          e_mail: 'alicialevy@memora.com',
          date_created: '4/28/2013',
          date_updated: '4/28/2013'
        },
        {
          first_name: 'Jacquelyn',
          middle_name: 'Tucker',
          last_name: 'Moran',
          address_1: '598 Dorset Street',
          address_2: 'Lee Avenue',
          city: 2172,
          country: 'CHN',
          phone_number: '(812) 518-2918',
          cell_number: '(973) 471-2910',
          birth_date: '4/1/1981',
          gender: 'Female',
          e_mail: 'jacquelynmoran@memora.com',
          date_created: '7/23/2013',
          date_updated: '7/23/2013'
        },
        {
          first_name: 'Charlene',
          middle_name: 'Sears',
          last_name: 'Turner',
          address_1: '523 Farragut Place',
          address_2: 'Seaview Avenue',
          city: 513,
          country: 'GBR',
          phone_number: '(983) 445-2440',
          cell_number: '(801) 487-2158',
          birth_date: '12/21/1988',
          gender: 'Male',
          e_mail: 'charleneturner@memora.com',
          date_created: '12/3/2010',
          date_updated: '12/3/2010'
        },
        {
          first_name: 'Gretchen',
          middle_name: 'Cooper',
          last_name: 'Holmes',
          address_1: '376 Ludlam Place',
          address_2: 'Varick Street',
          city: 567,
          country: 'CHL',
          phone_number: '(866) 480-2653',
          cell_number: '(911) 433-3877',
          birth_date: '5/12/1982',
          gender: 'Male',
          e_mail: 'gretchenholmes@memora.com',
          date_created: '3/31/2013',
          date_updated: '3/31/2013'
        },
        {
          first_name: 'Mabel',
          middle_name: 'Sanford',
          last_name: 'Douglas',
          address_1: '480 Moultrie Street',
          address_2: 'Montrose Avenue',
          city: 3467,
          country: 'UKR',
          phone_number: '(953) 570-2487',
          cell_number: '(826) 555-3746',
          birth_date: '2/9/1990',
          gender: 'Male',
          e_mail: 'mabeldouglas@memora.com',
          date_created: '5/10/2017',
          date_updated: '5/10/2017'
        },
        {
          first_name: 'Selena',
          middle_name: 'Saunders',
          last_name: 'Pugh',
          address_1: '533 Hall Street',
          address_2: 'Ross Street',
          city: 1979,
          country: 'CHN',
          phone_number: '(869) 571-3511',
          cell_number: '(988) 506-2976',
          birth_date: '1/20/1984',
          gender: 'Female',
          e_mail: 'selenapugh@memora.com',
          date_created: '7/9/2016',
          date_updated: '7/9/2016'
        },
        {
          first_name: 'Roman',
          middle_name: 'Ortiz',
          last_name: 'Jenkins',
          address_1: '586 Johnson Avenue',
          address_2: 'Ash Street',
          city: 1889,
          country: 'CAF',
          phone_number: '(938) 538-2710',
          cell_number: '(886) 521-2243',
          birth_date: '6/16/1975',
          gender: 'Male',
          e_mail: 'romanjenkins@memora.com',
          date_created: '3/11/2010',
          date_updated: '3/11/2010'
        },
        {
          first_name: 'Thelma',
          middle_name: 'Haley',
          last_name: 'Ochoa',
          address_1: '235 Middleton Street',
          address_2: 'Newkirk Placez',
          city: 1423,
          country: 'IRN',
          phone_number: '(976) 400-3240',
          cell_number: '(902) 439-2397',
          birth_date: '8/25/1963',
          gender: 'Male',
          e_mail: 'thelmaochoa@memora.com',
          date_created: '8/18/2016',
          date_updated: '8/18/2016'
        },
        {
          first_name: 'Georgia',
          middle_name: 'Boone',
          last_name: 'Livingston',
          address_1: '304 Halleck Street',
          address_2: 'Tennis Court',
          city: 1530,
          country: 'JAM',
          phone_number: '(807) 534-3141',
          cell_number: '(894) 549-3585',
          birth_date: '11/11/1997',
          gender: 'Female',
          e_mail: 'georgialivingston@memora.com',
          date_created: '12/17/2011',
          date_updated: '12/17/2011'
        },
        {
          first_name: 'Montgomery',
          middle_name: 'Ashley',
          last_name: 'Gross',
          address_1: '352 Strong Place',
          address_2: 'Wilson Avenue',
          city: 2856,
          country: 'PAK',
          phone_number: '(999) 441-2627',
          cell_number: '(911) 467-2832',
          birth_date: '10/6/1985',
          gender: 'Female',
          e_mail: 'montgomerygross@memora.com',
          date_created: '6/5/2014',
          date_updated: '6/5/2014'
        },
        {
          first_name: 'Madden',
          middle_name: 'Potts',
          last_name: 'Dawson',
          address_1: '686 Victor Road',
          address_2: 'Strickland Avenue',
          city: 2695,
          country: 'MCO',
          phone_number: '(931) 474-3065',
          cell_number: '(969) 424-2703',
          birth_date: '4/13/1969',
          gender: 'Female',
          e_mail: 'maddendawson@memora.com',
          date_created: '5/18/2016',
          date_updated: '5/18/2016'
        },
        {
          first_name: 'Shawna',
          middle_name: 'Chavez',
          last_name: 'Henry',
          address_1: '670 Heyward Street',
          address_2: 'Richmond Street',
          city: 185,
          country: 'BLZ',
          phone_number: '(876) 553-2472',
          cell_number: '(988) 548-3120',
          birth_date: '7/27/1986',
          gender: 'Male',
          e_mail: 'shawnahenry@memora.com',
          date_created: '10/5/2016',
          date_updated: '10/5/2016'
        },
        {
          first_name: 'Marks',
          middle_name: 'Robles',
          last_name: 'Poole',
          address_1: '655 Montauk Court',
          address_2: 'Junius Street',
          city: 1957,
          country: 'CHN',
          phone_number: '(991) 593-2892',
          cell_number: '(996) 460-3496',
          birth_date: '8/5/1967',
          gender: 'Female',
          e_mail: 'markspoole@memora.com',
          date_created: '11/29/2011',
          date_updated: '11/29/2011'
        },
        {
          first_name: 'Gayle',
          middle_name: 'Wagner',
          last_name: 'Newman',
          address_1: '434 Decatur Street',
          address_2: 'Middagh Street',
          city: 2161,
          country: 'CHN',
          phone_number: '(887) 515-3534',
          cell_number: '(852) 590-2537',
          birth_date: '2/4/1990',
          gender: 'Male',
          e_mail: 'gaylenewman@memora.com',
          date_created: '3/22/2016',
          date_updated: '3/22/2016'
        },
        {
          first_name: 'Buckley',
          middle_name: 'Lopez',
          last_name: 'Mendoza',
          address_1: '329 Tilden Avenue',
          address_2: 'Tudor Terrace',
          city: 3632,
          country: 'RUS',
          phone_number: '(871) 422-2887',
          cell_number: '(897) 449-2938',
          birth_date: '10/16/1992',
          gender: 'Female',
          e_mail: 'buckleymendoza@memora.com',
          date_created: '10/23/2010',
          date_updated: '10/23/2010'
        },
        {
          first_name: 'Dickson',
          middle_name: 'Olson',
          last_name: 'Bishop',
          address_1: '713 Oxford Walk',
          address_2: 'Bragg Court',
          city: 3986,
          country: 'USA',
          phone_number: '(902) 567-2828',
          cell_number: '(827) 429-2297',
          birth_date: '2/9/1972',
          gender: 'Male',
          e_mail: 'dicksonbishop@memora.com',
          date_created: '12/16/2010',
          date_updated: '12/16/2010'
        },
        {
          first_name: 'Ray',
          middle_name: 'Faulkner',
          last_name: 'Kemp',
          address_1: '963 Stone Avenue',
          address_2: 'Kansas Place',
          city: 907,
          country: 'GEO',
          phone_number: '(884) 470-3980',
          cell_number: '(973) 409-3456',
          birth_date: '12/2/1993',
          gender: 'Male',
          e_mail: 'raykemp@memora.com',
          date_created: '3/30/2015',
          date_updated: '3/30/2015'
        },
        {
          first_name: 'Booth',
          middle_name: 'Pickett',
          last_name: 'Willis',
          address_1: '826 Macon Street',
          address_2: 'Prospect Place',
          city: 1210,
          country: 'IND',
          phone_number: '(981) 553-2223',
          cell_number: '(924) 441-3129',
          birth_date: '4/22/1997',
          gender: 'Female',
          e_mail: 'boothwillis@memora.com',
          date_created: '5/17/2014',
          date_updated: '5/17/2014'
        },
        {
          first_name: 'Joni',
          middle_name: 'Delacruz',
          last_name: 'Gould',
          address_1: '614 Tapscott Avenue',
          address_2: 'Schroeders Avenue',
          city: 3765,
          country: 'RUS',
          phone_number: '(861) 442-3912',
          cell_number: '(907) 565-2120',
          birth_date: '1/28/1997',
          gender: 'Male',
          e_mail: 'jonigould@memora.com',
          date_created: '1/14/2010',
          date_updated: '1/14/2010'
        },
        {
          first_name: 'Donna',
          middle_name: 'Keith',
          last_name: 'Riley',
          address_1: '111 Dictum Court',
          address_2: 'Lafayette Avenue',
          city: 2360,
          country: 'KOR',
          phone_number: '(924) 422-2546',
          cell_number: '(945) 442-3697',
          birth_date: '10/30/1993',
          gender: 'Male',
          e_mail: 'donnariley@memora.com',
          date_created: '2/25/2014',
          date_updated: '2/25/2014'
        },
        {
          first_name: 'Caldwell',
          middle_name: 'Owen',
          last_name: 'Hogan',
          address_1: '582 Croton Loop',
          address_2: 'Kingsland Avenue',
          city: 2888,
          country: 'PRY',
          phone_number: '(913) 541-2229',
          cell_number: '(800) 494-3375',
          birth_date: '3/5/1983',
          gender: 'Female',
          e_mail: 'caldwellhogan@memora.com',
          date_created: '8/3/2017',
          date_updated: '8/3/2017'
        },
        {
          first_name: 'Potter',
          middle_name: 'Garrett',
          last_name: 'Hurley',
          address_1: '494 Arion Place',
          address_2: 'Seba Avenue',
          city: 3197,
          country: 'SEN',
          phone_number: '(957) 432-2045',
          cell_number: '(880) 587-3369',
          birth_date: '10/21/1988',
          gender: 'Female',
          e_mail: 'potterhurley@memora.com',
          date_created: '9/3/2015',
          date_updated: '9/3/2015'
        },
        {
          first_name: 'Evelyn',
          middle_name: 'Adkins',
          last_name: 'Simmons',
          address_1: '213 Eldert Street',
          address_2: 'Adelphi Street',
          city: 3065,
          country: 'LCA',
          phone_number: '(878) 430-2292',
          cell_number: '(942) 508-3984',
          birth_date: '4/22/1969',
          gender: 'Female',
          e_mail: 'evelynsimmons@memora.com',
          date_created: '7/31/2014',
          date_updated: '7/31/2014'
        },
        {
          first_name: 'Ladonna',
          middle_name: 'Travis',
          last_name: 'Nolan',
          address_1: '283 Fulton Street',
          address_2: 'Bayard Street',
          city: 3417,
          country: 'TUR',
          phone_number: '(981) 577-2854',
          cell_number: '(932) 562-3152',
          birth_date: '3/11/1964',
          gender: 'Male',
          e_mail: 'ladonnanolan@memora.com',
          date_created: '1/24/2016',
          date_updated: '1/24/2016'
        },
        {
          first_name: 'Gilbert',
          middle_name: 'Fitzgerald',
          last_name: 'Brock',
          address_1: '792 Garnet Street',
          address_2: 'Thomas Street',
          city: 3289,
          country: 'TWN',
          phone_number: '(816) 408-3566',
          cell_number: '(874) 503-2819',
          birth_date: '8/28/1997',
          gender: 'Female',
          e_mail: 'gilbertbrock@memora.com',
          date_created: '9/21/2012',
          date_updated: '9/21/2012'
        },
        {
          first_name: 'Gibbs',
          middle_name: 'Reed',
          last_name: 'Dunlap',
          address_1: '807 Roder Avenue',
          address_2: 'Seigel Street',
          city: 2800,
          country: 'NGA',
          phone_number: '(901) 547-3822',
          cell_number: '(949) 444-3862',
          birth_date: '3/9/1964',
          gender: 'Female',
          e_mail: 'gibbsdunlap@memora.com',
          date_created: '4/7/2014',
          date_updated: '4/7/2014'
        },
        {
          first_name: 'Watkins',
          middle_name: 'Baird',
          last_name: 'Blanchard',
          address_1: '845 Girard Street',
          address_2: 'Kensington Walk',
          city: 3641,
          country: 'RUS',
          phone_number: '(924) 417-2656',
          cell_number: '(821) 565-3357',
          birth_date: '2/14/1980',
          gender: 'Male',
          e_mail: 'watkinsblanchard@memora.com',
          date_created: '1/29/2016',
          date_updated: '1/29/2016'
        },
        {
          first_name: 'Mamie',
          middle_name: 'Lancaster',
          last_name: 'Rush',
          address_1: '954 Downing Street',
          address_2: 'Oceanview Avenue',
          city: 2854,
          country: 'PAK',
          phone_number: '(847) 486-2868',
          cell_number: '(967) 440-2015',
          birth_date: '4/21/1986',
          gender: 'Male',
          e_mail: 'mamierush@memora.com',
          date_created: '3/21/2010',
          date_updated: '3/21/2010'
        },
        {
          first_name: 'Adela',
          middle_name: 'Hansen',
          last_name: 'Mckee',
          address_1: '978 Reeve Place',
          address_2: 'Evans Street',
          city: 1929,
          country: 'CHN',
          phone_number: '(970) 420-2330',
          cell_number: '(816) 535-2762',
          birth_date: '7/8/1997',
          gender: 'Female',
          e_mail: 'adelamckee@memora.com',
          date_created: '8/7/2014',
          date_updated: '8/7/2014'
        },
        {
          first_name: 'Carissa',
          middle_name: 'Rollins',
          last_name: 'Riddle',
          address_1: '941 Winthrop Street',
          address_2: 'Dwight Street',
          city: 3646,
          country: 'RUS',
          phone_number: '(965) 499-2071',
          cell_number: '(993) 430-3608',
          birth_date: '5/31/1974',
          gender: 'Male',
          e_mail: 'carissariddle@memora.com',
          date_created: '7/12/2017',
          date_updated: '7/12/2017'
        },
        {
          first_name: 'Marta',
          middle_name: 'French',
          last_name: 'Reynolds',
          address_1: '663 Matthews Place',
          address_2: 'Whitwell Place',
          city: 3978,
          country: 'USA',
          phone_number: '(950) 475-2349',
          cell_number: '(906) 524-3789',
          birth_date: '3/13/1989',
          gender: 'Female',
          e_mail: 'martareynolds@memora.com',
          date_created: '4/7/2015',
          date_updated: '4/7/2015'
        },
        {
          first_name: 'Copeland',
          middle_name: 'Booth',
          last_name: 'Hurst',
          address_1: '194 Lawrence Street',
          address_2: 'Huron Street',
          city: 2695,
          country: 'MCO',
          phone_number: '(912) 405-2384',
          cell_number: '(932) 503-3595',
          birth_date: '8/20/1983',
          gender: 'Female',
          e_mail: 'copelandhurst@memora.com',
          date_created: '11/9/2014',
          date_updated: '11/9/2014'
        },
        {
          first_name: 'Julianne',
          middle_name: 'Johnston',
          last_name: 'Larson',
          address_1: '883 Hill Street',
          address_2: 'Greene Avenue',
          city: 2678,
          country: 'MEX',
          phone_number: '(841) 517-2808',
          cell_number: '(808) 461-3480',
          birth_date: '5/19/1961',
          gender: 'Male',
          e_mail: 'juliannelarson@memora.com',
          date_created: '1/25/2011',
          date_updated: '1/25/2011'
        },
        {
          first_name: 'Sharlene',
          middle_name: 'Lowe',
          last_name: 'Parsons',
          address_1: '821 Essex Street',
          address_2: 'Olive Street',
          city: 2431,
          country: 'CYP',
          phone_number: '(941) 415-2125',
          cell_number: '(805) 418-2131',
          birth_date: '12/27/1980',
          gender: 'Male',
          e_mail: 'sharleneparsons@memora.com',
          date_created: '6/27/2013',
          date_updated: '6/27/2013'
        },
        {
          first_name: 'Billie',
          middle_name: 'Valencia',
          last_name: 'Fowler',
          address_1: '362 Fillmore Avenue',
          address_2: 'Melba Court',
          city: 3011,
          country: 'FRA',
          phone_number: '(876) 439-3887',
          cell_number: '(896) 461-3824',
          birth_date: '10/31/1963',
          gender: 'Female',
          e_mail: 'billiefowler@memora.com',
          date_created: '10/7/2013',
          date_updated: '10/7/2013'
        },
        {
          first_name: 'Sheila',
          middle_name: 'Leach',
          last_name: 'Hubbard',
          address_1: '336 Cook Street',
          address_2: 'Story Street',
          city: 2075,
          country: 'CHN',
          phone_number: '(961) 412-3290',
          cell_number: '(817) 560-3447',
          birth_date: '1/2/1979',
          gender: 'Female',
          e_mail: 'sheilahubbard@memora.com',
          date_created: '10/30/2010',
          date_updated: '10/30/2010'
        },
        {
          first_name: 'Noelle',
          middle_name: 'Figueroa',
          last_name: 'Bowman',
          address_1: '392 Will Place',
          address_2: 'Bouck Court',
          city: 363,
          country: 'BRA',
          phone_number: '(995) 506-3435',
          cell_number: '(840) 483-2751',
          birth_date: '4/3/1964',
          gender: 'Female',
          e_mail: 'noellebowman@memora.com',
          date_created: '1/26/2014',
          date_updated: '1/26/2014'
        },
        {
          first_name: 'Elsie',
          middle_name: 'Mcintosh',
          last_name: 'Stephenson',
          address_1: '933 Kosciusko Street',
          address_2: 'Horace Court',
          city: 1206,
          country: 'IND',
          phone_number: '(916) 564-2421',
          cell_number: '(989) 460-3817',
          birth_date: '4/13/1963',
          gender: 'Male',
          e_mail: 'elsiestephenson@memora.com',
          date_created: '5/9/2012',
          date_updated: '5/9/2012'
        },
        {
          first_name: 'Whitney',
          middle_name: 'Cabrera',
          last_name: 'Grimes',
          address_1: '985 Woodside Avenue',
          address_2: 'Gain Court',
          city: 1780,
          country: 'YEM',
          phone_number: '(901) 449-2710',
          cell_number: '(955) 437-2880',
          birth_date: '2/4/1973',
          gender: 'Male',
          e_mail: 'whitneygrimes@memora.com',
          date_created: '6/18/2013',
          date_updated: '6/18/2013'
        },
        {
          first_name: 'Madeleine',
          middle_name: 'Hernandez',
          last_name: 'Welch',
          address_1: '521 Monaco Place',
          address_2: 'Oriental Court',
          city: 4057,
          country: 'USA',
          phone_number: '(861) 457-3289',
          cell_number: '(865) 448-2977',
          birth_date: '9/27/1976',
          gender: 'Male',
          e_mail: 'madeleinewelch@memora.com',
          date_created: '4/1/2017',
          date_updated: '4/1/2017'
        },
        {
          first_name: 'Cathryn',
          middle_name: 'Copeland',
          last_name: 'Puckett',
          address_1: '411 Johnson Street',
          address_2: 'Crescent Street',
          city: 2913,
          country: 'MNP',
          phone_number: '(802) 549-2538',
          cell_number: '(837) 500-3220',
          birth_date: '12/10/1990',
          gender: 'Male',
          e_mail: 'cathrynpuckett@memora.com',
          date_created: '1/24/2013',
          date_updated: '1/24/2013'
        },
        {
          first_name: 'Ortiz',
          middle_name: 'Stokes',
          last_name: 'Todd',
          address_1: '966 Schenck Court',
          address_2: 'Clinton Street',
          city: 3255,
          country: 'SYR',
          phone_number: '(989) 426-3988',
          cell_number: '(862) 483-3298',
          birth_date: '2/7/1982',
          gender: 'Male',
          e_mail: 'ortiztodd@memora.com',
          date_created: '5/3/2011',
          date_updated: '5/3/2011'
        },
        {
          first_name: 'Manuela',
          middle_name: 'Moses',
          last_name: 'Harvey',
          address_1: '507 Devon Avenue',
          address_2: 'Cypress Court',
          city: 3380,
          country: 'TUR',
          phone_number: '(940) 478-2180',
          cell_number: '(947) 496-3187',
          birth_date: '3/11/1987',
          gender: 'Male',
          e_mail: 'manuelaharvey@memora.com',
          date_created: '7/4/2011',
          date_updated: '7/4/2011'
        },
        {
          first_name: 'Gates',
          middle_name: 'Rocha',
          last_name: 'Morrison',
          address_1: '305 Kermit Place',
          address_2: 'Wilson Street',
          city: 2272,
          country: 'COL',
          phone_number: '(937) 596-3720',
          cell_number: '(829) 590-3732',
          birth_date: '9/2/1994',
          gender: 'Male',
          e_mail: 'gatesmorrison@memora.com',
          date_created: '2/23/2015',
          date_updated: '2/23/2015'
        },
        {
          first_name: 'Bennett',
          middle_name: 'Meadows',
          last_name: 'Henson',
          address_1: '814 Hegeman Avenue',
          address_2: 'Myrtle Avenue',
          city: 3813,
          country: 'USA',
          phone_number: '(942) 444-2810',
          cell_number: '(823) 591-2339',
          birth_date: '9/27/1965',
          gender: 'Male',
          e_mail: 'bennetthenson@memora.com',
          date_created: '7/16/2012',
          date_updated: '7/16/2012'
        },
        {
          first_name: 'Wagner',
          middle_name: 'Nieves',
          last_name: 'Fox',
          address_1: '813 Bay Avenue',
          address_2: 'Veterans Avenue',
          city: 2038,
          country: 'CHN',
          phone_number: '(972) 411-2516',
          cell_number: '(913) 580-2620',
          birth_date: '9/9/1989',
          gender: 'Male',
          e_mail: 'wagnerfox@memora.com',
          date_created: '2/25/2013',
          date_updated: '2/25/2013'
        },
        {
          first_name: 'Aguirre',
          middle_name: 'Griffin',
          last_name: 'Lynn',
          address_1: '448 Aitken Place',
          address_2: 'Thatford Avenue',
          city: 627,
          country: 'EGY',
          phone_number: '(849) 529-2490',
          cell_number: '(889) 482-2063',
          birth_date: '5/4/1961',
          gender: 'Male',
          e_mail: 'aguirrelynn@memora.com',
          date_created: '4/4/2012',
          date_updated: '4/4/2012'
        },
        {
          first_name: 'Madeline',
          middle_name: 'Wade',
          last_name: 'Mckinney',
          address_1: '591 Church Avenue',
          address_2: 'Underhill Avenue',
          city: 3092,
          country: 'DEU',
          phone_number: '(868) 497-3260',
          cell_number: '(992) 545-3095',
          birth_date: '7/17/1979',
          gender: 'Male',
          e_mail: 'madelinemckinney@memora.com',
          date_created: '6/12/2015',
          date_updated: '6/12/2015'
        },
        {
          first_name: 'Katy',
          middle_name: 'Gillespie',
          last_name: 'Gardner',
          address_1: '249 Randolph Street',
          address_2: 'Anchorage Place',
          city: 2005,
          country: 'CHN',
          phone_number: '(865) 507-3599',
          cell_number: '(833) 443-3875',
          birth_date: '8/4/1970',
          gender: 'Female',
          e_mail: 'katygardner@memora.com',
          date_created: '11/6/2013',
          date_updated: '11/6/2013'
        },
        {
          first_name: 'Lyons',
          middle_name: 'Powers',
          last_name: 'Foster',
          address_1: '692 Greenpoint Avenue',
          address_2: 'Tapscott Street',
          city: 2788,
          country: 'NGA',
          phone_number: '(945) 463-2429',
          cell_number: '(930) 576-2481',
          birth_date: '7/23/1990',
          gender: 'Male',
          e_mail: 'lyonsfoster@memora.com',
          date_created: '7/11/2015',
          date_updated: '7/11/2015'
        },
        {
          first_name: 'Justice',
          middle_name: 'Hayes',
          last_name: 'Merrill',
          address_1: '952 Harden Street',
          address_2: 'Tiffany Place',
          city: 3098,
          country: 'DEU',
          phone_number: '(850) 403-3075',
          cell_number: '(961) 538-3445',
          birth_date: '8/23/1977',
          gender: 'Female',
          e_mail: 'justicemerrill@memora.com',
          date_created: '9/9/2013',
          date_updated: '9/9/2013'
        },
        {
          first_name: 'Evangelina',
          middle_name: 'Beard',
          last_name: 'Gonzalez',
          address_1: '797 Union Street',
          address_2: 'Sutton Street',
          city: 1899,
          country: 'CHN',
          phone_number: '(995) 574-3190',
          cell_number: '(956) 526-3481',
          birth_date: '11/16/1986',
          gender: 'Female',
          e_mail: 'evangelinagonzalez@memora.com',
          date_created: '3/25/2011',
          date_updated: '3/25/2011'
        },
        {
          first_name: 'Melissa',
          middle_name: 'Huff',
          last_name: 'Spears',
          address_1: '738 Cadman Plaza',
          address_2: 'Fiske Place',
          city: 94,
          country: '#N/A',
          phone_number: '(863) 523-3053',
          cell_number: '(953) 578-3118',
          birth_date: '8/29/1990',
          gender: 'Male',
          e_mail: 'melissaspears@memora.com',
          date_created: '8/29/2010',
          date_updated: '8/29/2010'
        },
        {
          first_name: 'Hatfield',
          middle_name: 'Duran',
          last_name: 'Robertson',
          address_1: '534 Dekalb Avenue',
          address_2: 'Adams Street',
          city: 2523,
          country: 'MEX',
          phone_number: '(828) 530-3120',
          cell_number: '(964) 413-2408',
          birth_date: '6/16/1971',
          gender: 'Male',
          e_mail: 'hatfieldrobertson@memora.com',
          date_created: '12/1/2017',
          date_updated: '12/1/2017'
        },
        {
          first_name: 'Jan',
          middle_name: 'Cameron',
          last_name: 'Byers',
          address_1: '781 Jefferson Street',
          address_2: 'Crown Street',
          city: 2903,
          country: 'PER',
          phone_number: '(974) 545-2998',
          cell_number: '(886) 400-3850',
          birth_date: '10/31/1996',
          gender: 'Male',
          e_mail: 'janbyers@memora.com',
          date_created: '4/25/2017',
          date_updated: '4/25/2017'
        },
        {
          first_name: 'Essie',
          middle_name: 'Duffy',
          last_name: 'Suarez',
          address_1: '899 Adler Place',
          address_2: 'Lott Place',
          city: 370,
          country: 'BRA',
          phone_number: '(845) 413-2732',
          cell_number: '(822) 478-2642',
          birth_date: '7/1/1993',
          gender: 'Male',
          e_mail: 'essiesuarez@memora.com',
          date_created: '2/13/2016',
          date_updated: '2/13/2016'
        },
        {
          first_name: 'Collins',
          middle_name: 'Strong',
          last_name: 'Goff',
          address_1: '687 Veronica Place',
          address_2: 'Krier Place',
          city: 258,
          country: 'BRA',
          phone_number: '(848) 497-2911',
          cell_number: '(893) 540-3095',
          birth_date: '8/23/1993',
          gender: 'Male',
          e_mail: 'collinsgoff@memora.com',
          date_created: '5/3/2014',
          date_updated: '5/3/2014'
        },
        {
          first_name: 'Gordon',
          middle_name: 'Frost',
          last_name: 'Noel',
          address_1: '619 Campus Road',
          address_2: 'Bergen Court',
          city: 3346,
          country: 'CZE',
          phone_number: '(970) 475-3496',
          cell_number: '(952) 445-2475',
          birth_date: '5/5/1992',
          gender: 'Male',
          e_mail: 'gordonnoel@memora.com',
          date_created: '6/28/2010',
          date_updated: '6/28/2010'
        },
        {
          first_name: 'Barry',
          middle_name: 'Hester',
          last_name: 'Vinson',
          address_1: '559 Jefferson Avenue',
          address_2: 'Butler Street',
          city: 3087,
          country: 'DEU',
          phone_number: '(864) 511-2057',
          cell_number: '(914) 582-3092',
          birth_date: '7/20/1974',
          gender: 'Male',
          e_mail: 'barryvinson@memora.com',
          date_created: '1/21/2012',
          date_updated: '1/21/2012'
        },
        {
          first_name: 'Sullivan',
          middle_name: 'Sharpe',
          last_name: 'Finley',
          address_1: '887 McKibbin Street',
          address_2: 'Denton Place',
          city: 1856,
          country: 'CAN',
          phone_number: '(863) 514-2055',
          cell_number: '(818) 412-3450',
          birth_date: '8/16/1966',
          gender: 'Female',
          e_mail: 'sullivanfinley@memora.com',
          date_created: '2/13/2010',
          date_updated: '2/13/2010'
        },
        {
          first_name: 'Mcleod',
          middle_name: 'Beach',
          last_name: 'Mccormick',
          address_1: '467 Calder Place',
          address_2: 'Henderson Walk',
          city: 3888,
          country: 'USA',
          phone_number: '(908) 402-3348',
          cell_number: '(937) 437-3882',
          birth_date: '4/30/1971',
          gender: 'Male',
          e_mail: 'mcleodmccormick@memora.com',
          date_created: '3/1/2014',
          date_updated: '3/1/2014'
        },
        {
          first_name: 'Daniels',
          middle_name: 'Estrada',
          last_name: 'Morgan',
          address_1: '764 Crosby Avenue',
          address_2: 'Noel Avenue',
          city: 1590,
          country: 'JPN',
          phone_number: '(841) 486-2637',
          cell_number: '(888) 435-2697',
          birth_date: '9/24/1968',
          gender: 'Female',
          e_mail: 'danielsmorgan@memora.com',
          date_created: '8/3/2016',
          date_updated: '8/3/2016'
        },
        {
          first_name: 'Kerry',
          middle_name: 'Montgomery',
          last_name: 'Andrews',
          address_1: '892 Hart Place',
          address_2: 'Heath Place',
          city: 2757,
          country: 'NGA',
          phone_number: '(992) 460-3715',
          cell_number: '(842) 538-3746',
          birth_date: '9/14/1966',
          gender: 'Female',
          e_mail: 'kerryandrews@memora.com',
          date_created: '12/24/2013',
          date_updated: '12/24/2013'
        },
        {
          first_name: 'Lester',
          middle_name: 'Blevins',
          last_name: 'Williamson',
          address_1: '869 Grand Street',
          address_2: 'Ocean Parkway',
          city: 784,
          country: 'PHL',
          phone_number: '(984) 525-3488',
          cell_number: '(809) 434-2446',
          birth_date: '4/3/1969',
          gender: 'Female',
          e_mail: 'lesterwilliamson@memora.com',
          date_created: '3/9/2013',
          date_updated: '3/9/2013'
        },
        {
          first_name: 'Schroeder',
          middle_name: 'Wilder',
          last_name: 'Burke',
          address_1: '327 Bush Street',
          address_2: 'Imlay Street',
          city: 2677,
          country: 'MEX',
          phone_number: '(954) 411-2672',
          cell_number: '(801) 430-2117',
          birth_date: '8/21/1976',
          gender: 'Male',
          e_mail: 'schroederburke@memora.com',
          date_created: '8/23/2012',
          date_updated: '8/23/2012'
        },
        {
          first_name: 'Sybil',
          middle_name: 'Baxter',
          last_name: 'Wall',
          address_1: '941 Joval Court',
          address_2: 'Harway Avenue',
          city: 2516,
          country: 'MEX',
          phone_number: '(886) 485-3785',
          cell_number: '(805) 532-2465',
          birth_date: '4/14/1967',
          gender: 'Male',
          e_mail: 'sybilwall@memora.com',
          date_created: '12/21/2014',
          date_updated: '12/21/2014'
        },
        {
          first_name: 'Celeste',
          middle_name: 'Rhodes',
          last_name: 'Howell',
          address_1: '123 Hanson Place',
          address_2: 'Village Road',
          city: 3914,
          country: 'USA',
          phone_number: '(843) 525-2887',
          cell_number: '(814) 508-3499',
          birth_date: '12/12/1963',
          gender: 'Female',
          e_mail: 'celestehowell@memora.com',
          date_created: '12/10/2015',
          date_updated: '12/10/2015'
        },
        {
          first_name: 'Dean',
          middle_name: 'Vaughan',
          last_name: 'Porter',
          address_1: '984 Turnbull Avenue',
          address_2: 'Duffield Street',
          city: 572,
          country: 'CHL',
          phone_number: '(925) 402-2687',
          cell_number: '(802) 442-2595',
          birth_date: '8/24/1993',
          gender: 'Male',
          e_mail: 'deanporter@memora.com',
          date_created: '8/23/2016',
          date_updated: '8/23/2016'
        },
        {
          first_name: 'Trujillo',
          middle_name: 'Bond',
          last_name: 'Caldwell',
          address_1: '894 Friel Place',
          address_2: 'Aberdeen Street',
          city: 470,
          country: 'GBR',
          phone_number: '(911) 413-2367',
          cell_number: '(862) 549-3245',
          birth_date: '2/2/1992',
          gender: 'Female',
          e_mail: 'trujillocaldwell@memora.com',
          date_created: '12/16/2011',
          date_updated: '12/16/2011'
        },
        {
          first_name: 'England',
          middle_name: 'Pierce',
          last_name: 'Vazquez',
          address_1: '716 Hemlock Street',
          address_2: 'Vandervoort Place',
          city: 3900,
          country: 'USA',
          phone_number: '(813) 434-2174',
          cell_number: '(946) 600-3382',
          birth_date: '9/13/1962',
          gender: 'Male',
          e_mail: 'englandvazquez@memora.com',
          date_created: '4/17/2017',
          date_updated: '4/17/2017'
        },
        {
          first_name: 'Abby',
          middle_name: 'Stewart',
          last_name: 'Lamb',
          address_1: '325 Aster Court',
          address_2: 'Brown Street',
          city: 3049,
          country: 'SWE',
          phone_number: '(967) 493-3481',
          cell_number: '(813) 495-3092',
          birth_date: '10/4/1988',
          gender: 'Female',
          e_mail: 'abbylamb@memora.com',
          date_created: '2/28/2016',
          date_updated: '2/28/2016'
        },
        {
          first_name: 'Myra',
          middle_name: 'Reyes',
          last_name: 'Dickerson',
          address_1: '450 Keen Court',
          address_2: 'Boynton Place',
          city: 2204,
          country: 'CHN',
          phone_number: '(840) 521-2520',
          cell_number: '(976) 433-3704',
          birth_date: '11/29/1973',
          gender: 'Female',
          e_mail: 'myradickerson@memora.com',
          date_created: '4/25/2012',
          date_updated: '4/25/2012'
        },
        {
          first_name: 'Lola',
          middle_name: 'Fletcher',
          last_name: 'Blankenship',
          address_1: '700 Gunther Place',
          address_2: 'Ivan Court',
          city: 3789,
          country: 'VNM',
          phone_number: '(843) 425-3857',
          cell_number: '(894) 450-2575',
          birth_date: '11/3/1974',
          gender: 'Female',
          e_mail: 'lolablankenship@memora.com',
          date_created: '4/10/2012',
          date_updated: '4/10/2012'
        }
      ])
    })
}
